version: 0.0
os: linux
files:
    - source: /
      destination: /var/www/html
hooks:
  BeforeInstall:
    - location: scripts/BeforeInstall.sh
      timeout: 1800
      runas: root
  AfterInstall:
    - location: scripts/AfterInstall.sh
      timeout: 1800
      runas : root
